const packageTests = [
  {
    id: 1,
    name: "Basic Health Package I",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CBC (Complete Blood Count)",
      "Fasting Blood Sugar (FBS)",
      "HbA1c",
      "Total cholesterol / Sr Triglycerides",
      "Kidney Function Test (KFT)",
      "SGOT / SGPT / Total Bilirubin",
      "TSH",
      "Urine routine",
    ],
  },

  {
    id: 2,
    name: "Basic Health Package II",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CCBC",
      "CRP",
      "FBS / RBS",
      "HbA1c",
      "Liver Function Test (LFT)",
      "Kidney Function Test (KFT)",
      "Lipid Profile",
      "Thyroid Profile (FT3, FT4, TSH)",
      "Sr Electrolytes (Sodium, Potassium, Chloride)",
      "Vitamin D, Vitamin B12",
      "Sr Iron",
      "Sr Uric acid",
      "Urine routine",
    ],
  },

  {
    id: 3,
    name: "Comprehensive Health Package",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CBC",
      "CRP",
      "FBS & PPBS (Postprandial Blood Sugar)",
      "HbA1c",
      "Liver Function Test (LFT)",
      "Kidney Function Test (KFT)",
      "Lipid Profile",
      "Thyroid Profile (FT3, FT4, TSH)",
      "Sr Electrolytes (Sodium, Potassium, Chloride)",
      "PT INR, APTT",
      "Iron studies",
      "Vitamin D & B12",
      "Calcium, Magnesium, Phosphorous",
      "Uric acid",
      "Urine routine",
    ],
  },

  {
    id: 4,
    name: "Diabetes & Nephro Package",
    price: 140,
    excisting_price: 140,
    benefits: [
      "Fasting & PPBS",
      "HbA1c",
      "Insulin (Fasting)",
      "Lipid Profile",
      "Serum Creatinine",
      "Blood Urea Nitrogen (BUN)",
      "Uric Acid",
      "Electrolytes (Na, K, Cl)",
      "eGFR",
      "Urine routine",
      "Urine microalbumin",
    ],
  },

  {
    id: 5,
    name: "Cardiac Package",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CBC",
      "KFT",
      "HbA1C",
      "Sr Electrolytes",
      "Hs-CRP",
      "Troponin-I",
      "ECG ",
      "Homocysteine",
      "Apolipoproteins A1 & B",
      "PT INR, APTT",
    ],
  },

  {
    id: 6,
    name: "Female Wellness Package",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CBC",
      "Thyroid Profile",
      "Lipid profile",
      "Kidney function test",
      "Liver function test",
      "Fasting blood sugar ",
      "HbA1c",
      "RA Factor",
      "Vitamin D & B12",
      "Iron Studies",
      "Uric acid",
      "Pap Smear / HPV DNA",
      "Hormonal Profile (FSH, LH, Prolactin, Estrogen)",
      "Urine routine",
    ],
  },

  {
    id: 7,
    name: "Male Wellness Package",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CBC",
      "Fasting Blood Sugar & HbA1c",
      "Lipid Profile",
      "Liver Function Test (LFT)",
      "Kidney Function Test (KFT)",
      "Thyroid Profile (T3, T4, TSH)",
      "Vitamin D & B12",
      "PSA (Prostate-Specific Antigen)",
      "Testosterone (Total & Free)",
      "Uric acid",
      "RA Factor",
    ],
  },

  {
    id: 8,
    name: "Pregnancy Routine/Screening Package",
    price: 140,
    excisting_price: 140,
    benefits: [
      "Complete Blood Count (CBC)",
      "CRP",
      "Kidney function test",
      "SGOT /SGPT",
      "Total Cholesterol / Sr Triglycerides",
      "Blood Group & Rh Typing",
      "Thyroid Function Test (TSH, FT4)",
      "Fasting Blood Sugar",
      "HbA1c (if diabetic risk)",
      "Urine Routine & Culture",
      "HIV I & II",
      "Hepatitis B Surface Antigen (HBsAg)",
      "Hepatitis C (Anti-HCV)",
      "VDRL (Syphilis)",
      "TORCH Profile (Toxoplasmosis, Rubella, CMV, HSV)",
      "Double Marker / Quad Marker Test (gestational age-specific)",
    ],
  },

  {
    id: 9,
    name: "Pediatric Package (1–12 years)",
    price: 140,
    excisting_price: 140,
    benefits: [
      "CBC",
      "CRP",
      "Iron Studies (Serum Iron, Ferritin, TIBC)",
      "Vitamin D",
      "Vitamin B12",
      "Vitamin A",
      "Calcium & Phosphorus",
      "Thyroid Profile (TSH, T3, T4)",
      "Blood Glucose (Fasting)",
      "Urine Routine",
      "Stool Routine (optional for GI symptoms)",
    ],
  },

  {
    id: 10,
    name: "STD Screening",
    price: 140,
    excisting_price: 140,
    benefits: [
      "HIV I & II",
      "Hepatitis B Surface Antigen (HBsAg)",
      "Hepatitis C (Anti-HCV)",
      "VDRL (Syphilis)",
      "Chlamydia (NAAT/Urine or Swab)",
      "Gonorrhea (NAAT/Urine or Swab)",
      "Herpes Simplex Virus Type 1 & 2 (IgG antibodies)",
    ],
  },
];
export default packageTests;
