const packageTests = [
  {
    id: 1,
    name: "PCOD PROFILE",
    price: 253,
    excisting_price: 340,
    benefits: [
      "Testosterone",
      "Insulin Fasting",
      "Estradiol / Oestrogen (E2)",
      "Luteinising Hormone (LH)",
      "Liver Profile",
      "Prolactin (PRL)",
      "Follicle Stimulating Hormone (FSH)",
      "Thyroid-Stimulating Hormone (TSH)",
      "Complete Blood Count",
      "Lipid Profile",
      "Kidney Function Test",
      "Iron Profile",
      "Diabetes Screen",
    ],
  },

  {
    id: 2,
    name: "PREGNANCY PROFILE",
    price: 258,
    excisting_price: 400,
    benefits: [
      "Vitamin D (Total)",
      "Vitamin B12",
      "Folate",
      "Ferritin",
      "Anti Hepatitis C Virus Antibody",
      "Hepatis B Surface Antigen",
      "HIV P24 Ag / Ab",
      "Total Triiodothyronine (T3)",
      "Total Thyroxine (T4)",
      "Thyroid Stimulating Hormone (TSH)",
      "Complete Blood Count",
      "Diabetes Screen",
      "Liver Profile",
      "Kidney Function Test",
      "Iron Profile",
      "Lipid Profile",
    ],
  },

  {
    id: 3,
    name: "BASIC DIABETES PACKAGE",
    price: 250,
    excisting_price: 300,
    benefits: [
      "Thyroid-Stimulating Hormone (TSH)",
      "Serum Electrolytes",
      "Iron Profile",
      "Complete Blood Count",
      "Liver Profile",
      "Diabetes Screen",
      "Kidney Function Test",
      "Lipid Profile",
    ],
  },

  {
    id: 4,
    name: "STANDARD WELLNESS PACKAGE",
    price: 250,
    excisting_price: 320,
    benefits: [
      "Free Thyroxine (FT4)",
      "Free Triiodothyronine (FT3)",
      "Thyroid-Stimulating Hormone (TSH)",
      "Complete Blood Count",
      "Liver Profile",
      "Kidney Function Test",
      "Lipid Profile",
      "Diabetes Screen",
      "Iron Profile",
      "Vitamin D (Total)",
      "Vitamin B12",
      "Testosterone",
    ],
  },

  {
    id: 5,
    name: "INFECTION PROFILE",
    price: 255,
    excisting_price: 380,
    benefits: [
      "HIV P24 Ag / Ab",
      "Hepatitis B Surface Antigen",
      "Anti Hepatitis C Virus Antibody",
      "Thyroid-Stimulating Hormone (TSH)",
      "Diabetes Screen",
      "Kidney Function Test",
      "Complete Blood Count",
      "Lipid Profile",
      "Liver Profile",
      "Iron Profile",
    ],
  },

  {
    id: 6,
    name: "OBESITY PROFILE",
    price: 250,
    excisting_price: 300,
    benefits: [
      "Vitamin D (Total)",
      "Vitamin B12",
      "Insulin Fasting",
      "Thyroid-Stimulating Hormone (TSH)",
      "Diabetes Screen",
      "Kidney Function Test",
      "Liver Profile",
      "Lipid Profile",
      "Iron Profile",
      "Testosterone",
      "Complete Blood Count",
    ],
  },

  {
    id: 7,
    name: "INFERTILITY PROFILE",
    price: 260,
    excisting_price: 320,
    benefits: [
      "Vitamin D (Total)",
      "Vitamin B12",
      "Thyroid-Stimulating Hormone (TSH)",
      "Complete Blood Count",
      "Luteinising Hormone (LH)",
      "Prolactin (PRL)",
      "Follicle Stimulating Hormone (FSH)",
      "Liver Profile",
      "Lipid Profile",
      "Iron Profile",
      "Diabetes Screen",
      "Folate",
      "Testosterone",
      "Kidney Function Test",
    ],
  },

  // {
  //   id: 8,
  //   name: "Pregnancy Routine/Screening Package",
  //   price: 1900,
  //   excisting_price: 2200,
  //   benefits: [
  //     "Complete Blood Count (CBC)",
  //     "CRP",
  //     "Kidney function test",
  //     "SGOT /SGPT",
  //     "Total Cholesterol / Sr Triglycerides",
  //     "Blood Group & Rh Typing",
  //     "Thyroid Function Test (TSH, FT4)",
  //     "Fasting Blood Sugar",
  //     "HbA1c (if diabetic risk)",
  //     "Urine Routine & Culture",
  //     "HIV I & II",
  //     "Hepatitis B Surface Antigen (HBsAg)",
  //     "Hepatitis C (Anti-HCV)",
  //     "VDRL (Syphilis)",
  //     "TORCH Profile (Toxoplasmosis, Rubella, CMV, HSV)",
  //     "Double Marker / Quad Marker Test (gestational age-specific)",
  //   ],
  // },

  // {
  //   id: 9,
  //   name: "Pediatric Package (1–12 years)",
  //   price: 550,
  //   excisting_price: 670,
  //   benefits: [
  //     "CBC",
  //     "CRP",
  //     "Iron Studies (Serum Iron, Ferritin, TIBC)",
  //     "Vitamin D",
  //     "Vitamin B12",
  //     "Vitamin A",
  //     "Calcium & Phosphorus",
  //     "Thyroid Profile (TSH, T3, T4)",
  //     "Blood Glucose (Fasting)",
  //     "Urine Routine",
  //     "Stool Routine (optional for GI symptoms)",
  //   ],
  // },

  // {
  //   id: 10,
  //   name: "STD Screening",
  //   price: 1800,
  //   excisting_price: 2200,
  //   benefits: [
  //     "HIV I & II",
  //     "Hepatitis B Surface Antigen (HBsAg)",
  //     "Hepatitis C (Anti-HCV)",
  //     "VDRL (Syphilis)",
  //     "Chlamydia (NAAT/Urine or Swab)",
  //     "Gonorrhea (NAAT/Urine or Swab)",
  //     "Herpes Simplex Virus Type 1 & 2 (IgG antibodies)",
  //   ],
  // },
];
export default packageTests;
